name: builder
description: "Drop applications for your store instantly"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.2.3
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  go_router: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter_28pt-Thin.ttf
          weight: 200
        - asset: assets/fonts/Inter_28pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_28pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_28pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_28pt-ExtraBold.ttf
          weight: 800
